server:
  port: 9090

spring:
  h2:
    console:
      enabled: true                       # use H2 web Console
      path: /board                        # web path

  datasource:
    driver-class-name: org.h2.Driver      # H2 driver setting
    url: jdbc:h2:mem:board;MODE=MySQL
    username: board
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true                  # Pretty Query
  thymeleaf:
    cache: false
logging:
  level:
    root: WARN
    me.ghsong.board: DEBUG
    org.springframework.web: ERROR
    org.springframework.security: WARN
    org.hibernate.type: trace             # Query ? -> view
