--INSERT INTO MEMBER (MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_MOBILE, CREATE_AT, UPDATED_AT) VALUES ('admin', 'admin', '관리자', '010-0000-0000', NOW(), NOW())
--INSERT INTO MEMBER (MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_MOBILE, CREATE_AT, UPDATED_AT) VALUES ('user', 'user', '사용자', '010-1111-2222', NOW(), NOW())
SELECT NOW()
